name = "rifky-backend"
main = "dist/worker.js"
compatibility_date = "2025-10-11"
compatibility_flags = []
workers_dev = true

[build]
command = "bun run build"

[[d1_databases]]
binding = "DB"
database_name = "rifky-contacts"
database_id = "961fc686-ca76-4b56-949a-4b9eb6929b51" # Run: wrangler d1 create rifky-contacts

